tests:
    stage: test
    image: registry.gitlab.com/craigbarnes/dockerfiles/lua-testing
    script:
        - apt-get update && apt-get -y install libsass-dev
        - for v in 5.3 5.2 5.1; do
              luarocks-$v make SASS_LIBDIR=/usr/lib/x86_64-linux-gnu
              && lua$v test.lua ;
          done
